Models/Sold_Property.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace House_Rental_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold_Property
    {
        public int Sold_Id { get; set; }
        public int Property_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Seller_Id { get; set; }
        public int Deposit_Amount { get; set; }
        public int Rental_Amount { get; set; }
        public string Date_of_Sale { get; set; }
    
        public virtual Customer_Details Customer_Details { get; set; }
        public virtual Property_Details Property_Details { get; set; }
        public virtual Seller_Details Seller_Details { get; set; }
    }
}

Controllers/SellerController.cs
using House_Rental_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Windows;

namespace House_Rental_System.Controllers
{
    public class SellerController : Controller
    {
        // GET: Seller
        House_Rental Db = new House_Rental();
        public ActionResult Index()
        {
            int id = (int)Session["sellerid"];
            List<Property_Details> pd = Db.Property_Details.Where(m => m.Seller_Id==id).ToList<Property_Details>();
            int i = 0;
            int[] property_count = new int[pd.Count];
            foreach(var x in pd)
            {
                var result = Db.Booking_Details.Where(m => m.Property_Id == x.Property_ID).Count();
                if (result == 0)
                {
                    property_count[i] = 0;
                }
                else
                {
                    property_count[i] = 1;
                }
                i += 1;
            }
            ViewBag.pc = property_count;
            
            return View(pd);
        }
        public ActionResult Indexs()
        {
            int id = (int)Session["sellerid"];
            List<Property_Details> pd = Db.Property_Details.Where(m => m.Seller_Id == id).ToList<Property_Details>();
            return View(pd);
        }
        public ActionResult AddProperty()
        {
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "House", Value = "House" });
            li.Add(new SelectListItem { Text = "Flat", Value = "Flat" });
            ViewData["type"] = li;
            List<SelectListItem> bhk = new List<SelectListItem>();
            bhk.Add(new SelectListItem { Text = "1Bhk", Value = "1BHK" });
            bhk.Add(new SelectListItem { Text = "2Bhk", Value = "2BHK" });
            bhk.Add(new SelectListItem { Text = "3Bhk", Value = "3BHK" });
            bhk.Add(new SelectListItem { Text = "4Bhk", Value = "4BHK" });
            bhk.Add(new SelectListItem { Text = "5Bhk", Value = "5BHK" });
            ViewData["bhk"] = bhk;
            List<SelectListItem> facing = new List<SelectListItem>();
            facing.Add(new SelectListItem { Text = "North", Value = "North" });
            facing.Add(new SelectListItem { Text = "East", Value = "East" });
            facing.Add(new SelectListItem { Text = "West", Value = "West" });
            facing.Add(new SelectListItem { Text = "South", Value = "South" });
            ViewData["facing"] = facing;
            List<SelectListItem> furnish = new List<SelectListItem>();
            furnish.Add(new SelectListItem { Text = "Fully Furnished", Value = "Fully Furnished" });
            furnish.Add(new SelectListItem { Text = "Semi Furnished", Value = "Semi Furnished" });
            furnish.Add(new SelectListItem { Text = "Not Furnished", Value = "Not Furnished" });
            ViewData["furnish"] = furnish;
            List<SelectListItem> tenant = new List<SelectListItem>();
            tenant.Add(new SelectListItem { Text = "Family", Value = "Family" });
            tenant.Add(new SelectListItem { Text = "Bacholer", Value = "Bacholer" });
            tenant.Add(new SelectListItem { Text = "Family/Bacholer", Value = "Family/Bacholer" });
            ViewData["tenant"] = tenant;
            List<SelectListItem> parking = new List<SelectListItem>();
            parking.Add(new SelectListItem { Text = "Available", Value = "Available" });
            parking.Add(new SelectListItem { Text = "Not Available", Value = "Not Available" });
            ViewData["parking"] = parking;
            List<SelectListItem> status = new List<SelectListItem>();
            status.Add(new SelectListItem { Text = "Available", Value = "Available" });
            status.Add(new SelectListItem { Text = "Not Available", Value = "Not Available" });
            ViewData["status"] = status;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult>AddProperty(Property_Details pd,HttpPostedFileBase[] images)
        {
            if (ModelState.IsValid)
            {
                pd.Seller_Id =(int) Session["sellerid"];
                
                
                Db.Property_Details.Add(pd);
                await Db.SaveChangesAsync();
   
                int id = Db.Property_Details.Max(p => p.Property_ID);
                if (images.Length>0)
                {
                    foreach (var image in images)
                    {
                        if (image != null)
                        {
                            BinaryReader binary = new BinaryReader(image.InputStream);
                            Property_Images pi = new Property_Images
                            {
                                Property_Id = id,
                                Image = binary.ReadBytes((int)image.ContentLength)
                            };
                            Db.Property_Images.Add(pi);
                        }
                        
                    }
                    Db.SaveChanges();
                }
                
               
            }
            else
            {
                List<SelectListItem> li = new List<SelectListItem>();
                li.Add(new SelectListItem { Text = "House", Value = "House" });
                li.Add(new SelectListItem { Text = "Flat", Value = "Flat" });
                ViewData["type"] = li;
                List<SelectListItem> bhk = new List<SelectListItem>();
                bhk.Add(new SelectListItem { Text = "1Bhk", Value = "1BHK" });
                bhk.Add(new SelectListItem { Text = "2Bhk", Value = "2BHK" });
                bhk.Add(new SelectListItem { Text = "3Bhk", Value = "3BHK" });
                bhk.Add(new SelectListItem { Text = "4Bhk", Value = "4BHK" });
                bhk.Add(new SelectListItem { Text = "5Bhk", Value = "5BHK" });
                ViewData["bhk"] = bhk;
                List<SelectListItem> facing = new List<SelectListItem>();
                facing.Add(new SelectListItem { Text = "North", Value = "North" });
                facing.Add(new SelectListItem { Text = "East", Value = "East" });
                facing.Add(new SelectListItem { Text = "West", Value = "West" });
                facing.Add(new SelectListItem { Text = "South", Value = "South" });
                ViewData["facing"] = facing;
                List<SelectListItem> furnish = new List<SelectListItem>();
                furnish.Add(new SelectListItem { Text = "Fully Furnished", Value = "Fully Furnished" });
                furnish.Add(new SelectListItem { Text = "Semi Furnished", Value = "Semi Furnished" });
                furnish.Add(new SelectListItem { Text = "Not Furnished", Value = "Not Furnished" });
                ViewData["furnish"] = furnish;
                List<SelectListItem> tenant = new List<SelectListItem>();
                tenant.Add(new SelectListItem { Text = "Family", Value = "Family" });
                tenant.Add(new SelectListItem { Text = "Bacholer", Value = "Bacholer" });
                tenant.Add(new SelectListItem { Text = "Family/Bacholer", Value = "Family/Bacholer" });
                ViewData["tenant"] = tenant;
                List<SelectListItem> parking = new List<SelectListItem>();
                parking.Add(new SelectListItem { Text = "Available", Value = "Available" });
                parking.Add(new SelectListItem { Text = "Not Available", Value = "Not Available" });
                ViewData["parking"] = parking;
                List<SelectListItem> status = new List<SelectListItem>();
                status.Add(new SelectListItem { Text = "Available", Value = "Available" });
                status.Add(new SelectListItem { Text = "Not Available", Value = "Not Available" });
                ViewData["status"] = status;
                return View(pd);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            Session["prop"] = id;
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property_Details property_Details = Db.Property_Details.Find(id);
            if (property_Details == null)
            {
                return HttpNotFound();
            }
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "House", Value = "House" });
            li.Add(new SelectListItem { Text = "Flat", Value = "Flat" });
            ViewData["type"] = li;
            List<SelectListItem> bhk = new List<SelectListItem>();
            bhk.Add(new SelectListItem { Text = "1Bhk", Value = "1BHK" });
            bhk.Add(new SelectListItem { Text = "2Bhk", Value = "2BHK" });
            bhk.Add(new SelectListItem { Text = "3Bhk", Value = "3BHK" });
            bhk.Add(new SelectListItem { Text = "4Bhk", Value = "4BHK" });
            bhk.Add(new SelectListItem { Text = "5Bhk", Value = "5BHK" });
            ViewData["bhk"] = bhk;
            List<SelectListItem> facing = new List<SelectListItem>();
            facing.Add(new SelectListItem { Text = "North", Value = "North" });
            facing.Add(new SelectListItem { Text = "East", Value = "East" });
            facing.Add(new SelectListItem { Text = "West", Value = "West" });
            facing.Add(new SelectListItem { Text = "South", Value = "South" });
            ViewData["facing"] = facing;
            List<SelectListItem> furnish = new List<SelectListItem>();
            furnish.Add(new SelectListItem { Text = "Fully Furnished", Value = "Fully Furnished" });

Views/Seller/AddProperty.cshtml
@model House_Rental_System.Models.Property_Details

@{
    ViewBag.Title = "AddProperty";
    Layout = "~/Views/Shared/_SellerLayout.cshtml";
}

<head>
    
    <link href="~/assets/form/css/style.css" rel="stylesheet" />
    <link href="~/assets/form/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />
</head>


<div class="wrapper">
    <div class="inner">
        @using (Html.BeginForm("AddProperty", "Seller", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <h3 class="text-dark">Property Details</h3>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Type</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Type, ViewData["type"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Type, "", new { @class = "text-danger" })
                        <i class="zmdi zmdi-home"></i>
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Name</label>
                    <div class="form-holder">
                        <i class="fas fa-house-user"></i>
                        @Html.EditorFor(model => model.Property_Name, new { htmlAttributes = new { @class = "form-control text-capitalize" } })
                        @Html.ValidationMessageFor(model => model.Property_Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Address</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-pin"></i>
                        @Html.EditorFor(model => model.Property_Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">State</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-city"></i>
                        @Html.EditorFor(model => model.Property_State, new { htmlAttributes = new { @class = "form-control text-capitalize" } })
                        @Html.ValidationMessageFor(model => model.Property_State, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">City</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-city"></i>
                        @Html.EditorFor(model => model.Property_City, new { htmlAttributes = new { @class = "form-control text-capitalize" } })
                        @Html.ValidationMessageFor(model => model.Property_City, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Pin</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-pin"></i>
                        @Html.EditorFor(model => model.Property_Pin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Pin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Expected Rent</label>
                    <div class="form-holder">
                        <i class="fa fa-rupee"></i>
                        @Html.EditorFor(model => model.Property_Information.ExpectedRent, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.ExpectedRent, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Expected Deposit</label>
                    <div class="form-holder">
                        <i class="fa fa-rupee"></i>
                        @Html.EditorFor(model => model.Property_Information.Expected_Deposit, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.Expected_Deposit, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">BHK</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Information.BHK, ViewData["bhk"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Information.BHK, "", new { @class = "text-danger" })
                        <i class="fa fa-bed"></i>
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Facing</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Information.Facing, ViewData["facing"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Information.Facing, "", new { @class = "text-danger" })
                        <i class="zmdi zmdi-arrows"></i>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Furnishing</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Information.Furnishing, ViewData["furnish"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Information.Furnishing, "", new { @class = "text-danger" })
                        <i class="fa fa-bed"></i>
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Preferred Tenants</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Information.Preferred_Tenants, ViewData["tenant"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Information.Preferred_Tenants, "", new { @class = "text-danger" })
                        <i class="zmdi zmdi-face"></i>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Property Age</label>
                    <div class="form-holder">
                        <i class="fa fa-font"></i>
                        @Html.EditorFor(model => model.Property_Information.Age, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.Age, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Size</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-ruler"></i>
                        @Html.EditorFor(model => model.Property_Information.Size, new { htmlAttributes = new { @class = "form-control",placeholder="in sqft" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.Size, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Floor</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-city"></i>
                        @Html.EditorFor(model => model.Property_Information.Floor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.Floor, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Total Floor</label>
                    <div class="form-holder">
                        <i class="zmdi zmdi-city"></i>
                        @Html.EditorFor(model => model.Property_Information.Total_Floor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Property_Information.Total_Floor, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Parking</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Information.Parking, ViewData["parking"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Information.Parking, "", new { @class = "text-danger" })
                        <i class="zmdi zmdi-car"></i>
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Status</label>
                    <div class="form-holder select">
                        @Html.DropDownListFor(model => model.Property_Status, ViewData["status"] as List<SelectListItem>, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Property_Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Property Images</label>
                    <div class="form-holder">

                        
                        <input type="file" id="image" name="images" class="form-control"; multiple />
                    </div>
                </div>

            </div>
            <center>
                <button class="btn btn-md px-4 text-white bg-success" type="submit">Add Property</button>
            </center>
                
            
        }
        </div>
        
    </div>
    

Views/Seller/Confirmation.cshtml
@model House_Rental_System.Models.Sold_Property

@{
    ViewBag.Title = "Confirmation";
    Layout = "~/Views/Shared/_SellerLayout.cshtml";
}

<head>

    <link href="~/assets/form/css/style.css" rel="stylesheet" />
    <link href="~/assets/form/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />
</head>
<div class="wrapper">
    <div class="inner">
        @using (Html.BeginForm("Confirmation", "Seller", FormMethod.Post, new { cid = ViewBag.cid, pid = ViewBag.pid }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h3 class="text-dark">Confirmation</h3>
            <div class="form-group">
                <div class="form-wrapper">
                    <label for="">Deposit Amount</label>
                    <div class="form-holder">
                        <i class="fa fa-rupee"></i>
                        @Html.EditorFor(model => model.Deposit_Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Deposit_Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-wrapper">
                    <label for="">Rent Amount</label>
                    <div class="form-holder">
                        <i class="fa fa-rupee"></i>
                        @Html.EditorFor(model => model.Rental_Amount, new { htmlAttributes = new { @class = "form-control text-capitalize" } })
                        @Html.ValidationMessageFor(model => model.Rental_Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <center>
                <button class="btn btn-success px-4" type="submit">  Confirm</button>
            </center>
        }
    </div>
</div>

Views/Seller/DeleteProperty.cshtml
@model House_Rental_System.Models.Property_Details

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Property_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Property_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Pin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Pin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seller_Details.Seller_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seller_Details.Seller_Name)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Seller",new { id = Model.Property_ID })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Seller/Index.cshtml
@model IEnumerable<House_Rental_System.Models.Property_Details>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SellerLayout.cshtml";
}
<head>
    <link href="~/assets/form/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />
</head>
<div class="container" style="margin-top:1%;">
    <div class="row">
        @foreach (var item in Model)
        {

            <div class="col-sm-4">
                <div class="card">
                    @{
                        var images = item.Property_Images;
                        if (images.Count > 0)
                        {
                            var base64 = Convert.ToBase64String(images[0].Image);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <img src='@imgsrc' style="height:200px;width:100%; border-radius:4px;" />
                        }

                    }
                    <div class="card-body">
                        <h5 class="card-title">@item.Property_Name</h5>
                        <p class="card-text zmdi zmdi-pin">  <b>Address</b>  @item.Property_Address , @item.Property_City (@item.Property_Pin)</p>
                        <p class="card-text fa fa-bed">  <b>BHK</b>  @item.Property_Information.BHK</p><br />
                        <p class="card-text fa fa-rupee">  <b>Deposit</b>  @item.Property_Information.Expected_Deposit</p><br />
                        <p class="card-text fa fa-rupee">  <b>Rent</b>  @item.Property_Information.ExpectedRent</p><br />
                        
                        <a href="~/Seller/Edit/@item.Property_ID" class="btn fa fa-edit btn-sm bg-info text-white">  Edit</a> 
                        <a href="~/Seller/Requests/@item.Property_ID" class="btn fa fa-mail-bulk btn-sm bg-primary float-right text-white">  Request</a>
                        
                    </div>
                </div>
            </div>


        }
    </div>
</div>

Views/Seller/SoldProperty.cshtml
@model IEnumerable<House_Rental_System.Models.Sold_Property>

@{
    ViewBag.Title = "SoldProperty";
    Layout = "~/Views/Shared/_SellerLayout.cshtml";
}

<div class="table-responsive">
    <table class="table  table-striped" style="margin-top:1%;">
        <tr class="table-dark">
            <th>
                Deposit

            </th>
            <th>
                Rent

            </th>
            <th>
                Date of Sale

            </th>
            <th>
                Customer Name

            </th>
            <th>
                Property Type

            </th>
            
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Deposit_Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rental_Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_of_Sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer_Details.Customer_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Property_Details.Property_Type)
                </td>
            </tr>
        }

    </table>
</div>